[package]
name = "y25d10"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils.workspace = true
itertools.workspace = true
rstest.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
log = "0.4.27"
derive_more = { version = "2.1.0", default-features = false, features = [
    "from",
    "constructor",
] }
good_lp = { version = "1.14.2", default-features = false, features = ["highs"] }

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "y25d10"
path = "benches/y25d10.rs"
harness = false
