[package]
name = "y25d11"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils.workspace = true
itertools.workspace = true
rstest.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
petgraph = "0.8.3"
rustc-hash = { version = "2.1" }


[dev-dependencies]
divan.workspace = true

[[bench]]
name = "y25d11"
path = "benches/y25d11.rs"
harness = false
