[package]
name = "y22d20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils.workspace = true
itertools.workspace = true
rstest.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "y22d20"
path = "benches/y22d20.rs"
harness = false
