[package]
name = "y22d21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils.workspace = true
itertools.workspace = true
rstest.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
petgraph = "0.8.3"
fxhash = "0.1.2"

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "y22d21"
path = "benches/y22d21.rs"
harness = false
