[package]
name = "y25d12"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils.workspace = true
itertools.workspace = true
rstest.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
rustsat = "0.7.4"
# rustsat-minisat = "0.7.4"
rustsat-kissat = "0.7.4"
rustc-hash = "2.1.1"
smallvec = "1.15.1"

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "y25d12"
path = "benches/y25d12.rs"
harness = false
